services:
  postgres:
    image: postgres:18
    container_name: labs-postgres
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: labs
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ../labs:/docker-entrypoint-initdb.d/sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U student -d labs"]
      interval: 5s
      timeout: 3s
      retries: 5

  adminer:
    image: adminer
    container_name: labs-adminer
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
